// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeuzuufqidrarmqveweh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldXp1dWZxaWRyYXJtcXZld2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDU0ODAsImV4cCI6MjA3MzkyMTQ4MH0.UMXI3RIZVqLlkyBb2ANI1NMruJmx68ArQgL_m7N2TvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});